### ISSUE TITLE
AttributeError: 'API' object has no attribute 'device'

### ISSUE THREAD

**Issue by aguilard07** [art-vasilyev/instachatbot#12]
Hi, I tried to run your example program but I got this error:
`AttributeError: 'API' object has no attribute 'device'`

**Comment by art-vasilyev** [comment]
Thank you for the issue, `instabot` package API has changed, so as a quick fix you may install `instabot==0.41`, I'll fix requirements.txt and release a new package soon

**Comment by art-vasilyev** [comment]
Version 0.3.2 was released
