### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by auctas** [art-vasilyev/instachatbot#19]
Hello,

I have a problem.

'QuestionnaireNode' I want to add another menu by removing the section that says

There will be 3 different categories, 2nd category will appear as a menu again.

I would appreciate your help

Sample;
menu = MenuNode(
    '💡Choose menu:\n',
    [
        MenuItem(
            'Menu-1',
            MessageNode('This is a message😀')),
        MenuItem(
            'Menu-2',
            menu = MenuNode (
            'Choose select',
            [
                MenuItem(
                'select-1',
                MessageNode('select-1 explanation')),
                MenuItem(
                'select-2',
                MessageNode('select-2 explanation')), 
            ],
            )
        MenuItem(
            'Menu-3',
            NotifyAdminNode(
                'Thank you',
                notification='Sample notification from bot user',
                admin_username='<username to send notification to>'
            )
        ),
    ],
    error_message='Failed to select menu.'
)

**Comment by art-vasilyev** [comment]
Hi @auctas, do you want something like this?
```
menu = MenuNode(
	'bulbChoose menu:\n',
	[
		MenuItem(
			'Menu-1',
			MessageNode('This is a messagegrinning')
		),
		MenuItem(
			'Menu-2',
			MenuNode(
				'Choose select',
				[
					MenuItem(
						'select-1',
						MessageNode('select-1 explanation')
					),
					MenuItem(
						'select-2',
						MessageNode('select-2 explanation')
					),
				],
			)
		),
		MenuItem(
			'Menu-3',
			NotifyAdminNode(
				'Thank you',
				notification='Sample notification from bot user',
				admin_username=''
			)
		),
	],
	error_message='Failed to select menu.'
)
```

**Comment by auctas** [comment]
Thank you so much :) 

> Hi @auctas, do you want something like this?
> 
> ```
> menu = MenuNode(
> 	'bulbChoose menu:\n',
> 	[
> 		MenuItem(
> 			'Menu-1',
> 			MessageNode('This is a messagegrinning')
> 		),
> 		MenuItem(
> 			'Menu-2',
> 			MenuNode(
> 				'Choose select',
> 				[
> 					MenuItem(
> 						'select-1',
> 						MessageNode('select-1 explanation')
> 					),
> 					MenuItem(
> 						'select-2',
> 						MessageNode('select-2 explanation')
> 					),
> 				],
> 			)
> 		),
> 		MenuItem(
> 			'Menu-3',
> 			NotifyAdminNode(
> 				'Thank you',
> 				notification='Sample notification from bot user',
> 				admin_username=''
> 			)
> 		),
> 	],
> 	error_message='Failed to select menu.'
> )
> ```

Thank you so much :) 👍
