### ISSUE TITLE
How to write certain keywords ?

### ISSUE THREAD

**Issue by BodyaGo** [art-vasilyev/instachatbot#20]
for example i write to bot -
 /menu it highlights my menu that I wrote etc.
I don't want the bot to send a menu for each of my messages

**Comment by art-vasilyev** [comment]
Hi, this feature is not supported yet, but I'm going to implement it soon

**Comment by art-vasilyev** [comment]
@BodyaGo ``trigger`` feature is merged, you can test it by installing from master branch. Package on pypi will be updated soon

**Comment by BodyaGo** [comment]
> @BodyaGo `trigger` feature is merged, you can test it by installing from master branch. Package on pypi will be updated soon

can u send link) артем проект топ нада розвивать

**Comment by BodyaGo** [comment]
артем спасибо большое , очень помог

**Comment by art-vasilyev** [comment]
@BodyaGo You are welcome! Latest package is on PyPI already: https://pypi.org/project/instachatbot/
